### ISSUE TITLE
Could you make a release?

### ISSUE THREAD

**Issue by skatpgusskat** [sayonari/twitchTransFreeNext#1]
Some people don't know how to download in Github.
So would you please make a release in Github?
like this, https://help.github.com/articles/creating-releases/

By the way, thank you for making this AWESOME app. I use this, people like this. Thank you! Arigoto Gojaimasu. :D

**Comment by sayonari** [comment]
Thanks!
I made a release now!

**Comment by skatpgusskat** [comment]
Is it ok to leave one more feedback?
If you start making release, it’s better remove executable files in git, like .exe file. 

Sometime it could be dangerous put executable file on git. If someone give you pull request with new code with new exe file, you cannot confirm that exe file is good file for hacking file. 
It is better that only authorized developer make release on release page, isn’t it?

**Comment by skatpgusskat** [comment]
Ok! Cool. Could you let me know if you make something awesome twitch-relative application? I have a big interest with that. 
Anyway, I close this issue. Thank you.
