### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AkumuMatata** [sayonari/twitchTransFreeNext#2]
Hi, 
I found this program and think it's amazing (I've seen it in action on other peoples streams). I've been trying to put it in my stream and keep getting an error message. I'm not sure what I'm doing wrong, is there a way that someone can show me a snap shot of what they did? Or even walk me through it.

Thank you!

**Comment by sayonari** [comment]
I think your config.txt is wrong! If you send it to me (sayonari@gmail.com), I will try to check it!

**Comment by AkumuMatata** [comment]
Thank you so much! I just sent you an email.

**Comment by rioai** [comment]
こんにちは私も上の人と同じくなぜかエラーを吐き続けます。
よくわからず困っています

**Comment by sayonari** [comment]
たまに，原因不明で動かない環境があるようです．
しかし，大抵はconfig.txtの設定間違い，記述エラーだと思います．
上の方と同じ様に，config.txtを私宛に送って頂ければチェックできます．
（oauth情報をそのまま記載するのが危険だと思われる場合には，そこを消して送ってください．）

**Comment by rioai** [comment]
ありがとうございます。すぐにおくります
