### ISSUE TITLE
Trans username not changing 

### ISSUE THREAD

**Issue by SquidSpearmint** [sayonari/twitchTransFreeNext#20]
Even though it is running through and seeing it in the command prompt, the name is not the same on my twitch channel. Was wondering if I did anything wrong here?

![image](https://user-images.githubusercontent.com/70742445/118348627-fa0be880-b58e-11eb-9750-8c1badb3c878.png)
 
![image](https://user-images.githubusercontent.com/70742445/118348640-11e36c80-b58f-11eb-9617-978fcfdf530c.png)

![image](https://user-images.githubusercontent.com/70742445/118488351-fd55ce80-b75e-11eb-86ff-ebf2d2fbe84c.png)

![image](https://user-images.githubusercontent.com/70742445/118488369-034baf80-b75f-11eb-9a52-7c35c7326321.png)

**Comment by sayonari** [comment]
I think you get the oauth key by using the account "umaisquiduwu".
You have to get the key by using the account "squidwaifu"

**Comment by SquidSpearmint** [comment]
> I think you get the oauth key by using the account "umaisquiduwu". You have to get the key by using the account "squidwaifu"

Well UmaiSquidUwU is the name of my twitch channel, so does that mean that I can only name the translator the same name as my channel?

**Comment by sayonari** [comment]
>
> that mean that I can only name the translator the same name as my channel?
>

No.

 This means, "When you got the current OAUTH key in your browser, didn't
you get it while logged in as umaisquiduwu? "
And it means, "When you get the OAUTH key in the browser, get it while you
are logged in with squidwaifu.

**Comment by SquidSpearmint** [comment]
> that mean that I can only name the translator the same name as my channel?
> No. This means, "When you got the current OAUTH key in your browser, didn't you get it while logged in as umaisquiduwu? " And it means, "When you get the OAUTH key in the browser, get it while you are logged in with squidwaifu.

Ohhhhhh I get it now!!! Thanks for the help!!! I got it to work now!

![image](https://user-images.githubusercontent.com/70742445/118641882-09549580-b81e-11eb-95dc-7123d09276ed.png)
