### ISSUE TITLE
DEEPL翻訳

### ISSUE THREAD

**Issue by kuroneko6423** [sayonari/twitchTransFreeNext#24]
![image](https://user-images.githubusercontent.com/42853476/124133470-d0fed300-dabc-11eb-9c84-8931300f0aa5.png)
動きません

**Comment by didotb** [comment]
@kuroneko6423 

私も興味があるので、協力したいです。

pythonのバージョン、`config.py`の情報（oauthは削除してください）、エラーなどの詳しい情報を記載してください。

エラーを表示するには、`config.py`を開いて、`Debug = False`を`Debug = True`に変更してください。

DeepL で翻訳されています。

**Comment by ddugovic** [comment]
Maybe try the following?

```
from langdetect import detect
```
```
    # 言語検出 -----------------------
    if config.Debug: print(f'--- Detect Language ---')
    lang_detect = detect(in_text)
```

**Comment by kuroneko6423** [comment]
> @kuroneko6423
> 
> 私も興味があるので、協力したいです。
> 
> pythonのバージョン、`config.py`の情報（oauthは削除してください）、エラーなどの詳しい情報を記載してください。
> 
> エラーを表示するには、`config.py`を開いて、`Debug = False`を`Debug = True`に変更してください。
> 
> DeepL で翻訳されています。

![image](https://user-images.githubusercontent.com/42853476/124388152-87acbe80-dd1c-11eb-903f-58690dc49d30.png)

**Comment by sayonari** [comment]
反応遅くてすみません．
原因はわかっていて， @ddugovic  さんのご指摘どおり，言語検出を別モジュールで行えば動きます．
そもそもの原因は，google_trans_new が，google翻訳の出力の変更に対応していないことです．
私から，google_trans_new にpullリクエストをおくりましたが，無反応です．

で，google_trans_new の修正方法は，そちらの僕のプルリクを見ていただきたいのですが，
@kuroneko6423 さんが，コケているのは，google_trans_new を修正したものの，transの方だけ直して， 言語検出用関数 detect の中身の，同様の変更を修正していないことによるものだと思います．

**Comment by didotb** [comment]
@sayonari 
DeepL を使用したい場合でも、GAS_URL を記述する必要がありますか？

-- Translated with DeepL
-- DeepL で翻訳されています。

**Comment by sayonari** [comment]
記述する必要はありません．

なお，
GAS_URLに入力がなければ，言語判定はgoogle_trans_newを使います．
入力があれば，GASを使います．
というふうになっているはずですが，もしかしたらバグっていて，違う挙動になっているかもしれません．

**Comment by kuroneko6423** [comment]
> Maybe try the following?
> 
> ```
> from langdetect import detect
> ```
> 
> ```
>     # 言語検出 -----------------------
>     if config.Debug: print(f'--- Detect Language ---')
>     lang_detect = detect(in_text)
> ```

![image](https://user-images.githubusercontent.com/42853476/124898951-9ba53880-e01a-11eb-88ac-0fc3365cb694.png)

**Comment by didotb** [comment]
@kuroneko6423 

> 記述する必要はありません．

DeepL をお使いですよね？
GAS_URLには何も書かなくてもよさそうです

**Comment by kuroneko6423** [comment]
> @kuroneko6423
> 
> > 記述する必要はありません．
> 
> DeepL をお使いですよね？
> GAS_URLには何も書かなくてもよさそうです
> 
> -- DeepL で翻訳されています
> -- Translated with DeepL

ですが翻訳された文字が出てきません。出てくるのは文字コードのみです

**Comment by didotb** [comment]
> ですが翻訳された文字が出てきません。出てくるのは文字コードのみです

Sayonari-san が翻訳機のバグを修正するために作った修正プログラムを試してみましたか？

**Comment by kuroneko6423** [comment]
> > ですが翻訳された文字が出てきません。出てくるのは文字コードのみです
> 
> Sayonari-san が翻訳機のバグを修正するために作った修正プログラムを試してみましたか？

はい
