### ISSUE TITLE
translator keeps spamming on its own and doesn't stop

### ISSUE THREAD

**Issue by Noku32** [sayonari/twitchTransFreeNext#47]
Hello everyone, I have been using the translator with success for a few months and it has been an enjoyable experience.  However, recently I had wanted to to try switch the transaltor engine to Deepl, and it gave me an error immediately.  I tried to revert back the changes and changed it back to 'google' but the translator kept spamming on its own and doesn't stop.  Even when I tried to create a new twitch account hoping that would solve the problem but it didn't work.  Here is the message that the translator kept spamming;

ACTION Action Action Action Action has landed! [3noku2translator] (JA> EN) [by 3noku2translator] (EN> JA) [by 3noku2translator] [by 3noku2translator] (ja > en)
アクションアクションアクションアクションアクションが上陸しました！ [3noku2translator]（ja> en）[by 3noku2translator]（en> ja）[by 3noku2translator]（ja> en） [by 3noku2translator] (en > ja)

It doesn't stop until it gets timed out.  Any help?

**Comment by sayonari** [comment]
It seems that the bot is translating its own text and posting them.
I wonder if there is some unintended bug in the configuration file. 
I recommend that you check the configuration file (config.py) or rebuild it from scratch.

**Comment by Noku32** [comment]
Thank you for the response!  I copied an older version of the translator from another PC and used it instead and the problem has been solved.
