### ISSUE TITLE
translate issue

### ISSUE THREAD

**Issue by BlossomchanTTV** [sayonari/twitchTransFreeNext#75]
![image_2024-11-14_021724220](https://github.com/user-attachments/assets/320d52cb-3794-4820-a8b8-e5fe783da2f5)
![image_2024-11-14_021835664](https://github.com/user-attachments/assets/30da2daa-17c1-46d0-b904-98d4f3401321)

i put everything correct.
but it doesnt translate.

**Comment by didotb** [comment]
https://github.com/sayonari/twitchTransFreeNext/commit/b59433ff33e9f84aa3f939fdf383aa8f8ca9f157 should fix the issue.

**Comment by BlossomchanTTV** [comment]
That worked! Thanks!

**Comment by didotb** [comment]
If you have no other concern, please don't forget to close this issue.
